# generate_ground_truth.R
#
# Run this script once (from the rrlmgraph-bench repo root, after
# rrlmgraph is installed) to regenerate the ground-truth RDS artefacts for
# the mini_ds_project fixture.
#
# Usage:
#   Rscript inst/ground_truth/generate_ground_truth.R
#
# The RDS files committed under inst/ground_truth/ were generated by this
# script and manually verified against the source code of the fixture.

fixture_dir <- file.path("inst", "projects", "mini_ds_project")
out_dir <- file.path("inst", "ground_truth")
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

# ---- 1. function_signatures.rds -------------------------------------
# Manually derived from the fixture source; no tooling needed.

function_signatures <- c(
  "data_prep::load_data" = "load_data(path)",
  "data_prep::clean_data" = "clean_data(df)",
  "data_prep::split_data" = "split_data(df, ratio = 0.8, ...)",
  "data_prep::split_data.data.frame" = "split_data.data.frame(df, ratio = 0.8, ...)",
  "models::fit_model" = "fit_model(train_data, formula)",
  "models::evaluate_model" = "evaluate_model(model, test_data, ...)",
  "models::evaluate_model.lm_result" = "evaluate_model.lm_result(model, test_data, ...)",
  "models::compute_rmse" = "compute_rmse(predicted, actual)",
  "benchmark::run_benchmark" = "run_benchmark(data_path, formula = score ~ .)",
  "benchmark::calculate_mrr" = "calculate_mrr(ranked_results)",
  "benchmark::format_results" = "format_results(results, digits = 3)"
)

saveRDS(function_signatures, file.path(out_dir, "function_signatures.rds"))
message(
  "Wrote function_signatures.rds (",
  length(function_signatures),
  " entries)"
)

# ---- 2. call_edges.rds -----------------------------------------------
# True CALLS edges — manually verified from reading the source.
# Format: data.frame(from, to)  where both are node_id strings.
#
# Key design note: NSE column names (score, id, score_z) used as arguments
# to dplyr verbs must NOT appear here.  mean() called inside mutate() IS a
# real function call and IS included.

call_edges <- data.frame(
  from = c(
    # load_data calls utils::read.csv
    "data_prep::load_data",
    # clean_data calls dplyr::filter, dplyr::mutate, and real fns inside mutate
    "data_prep::clean_data",
    "data_prep::clean_data",
    "data_prep::clean_data",
    "data_prep::clean_data",
    # split_data.data.frame calls nrow, floor, seq_len
    "data_prep::split_data.data.frame",
    "data_prep::split_data.data.frame",
    "data_prep::split_data.data.frame",
    # fit_model calls stats::lm
    "models::fit_model",
    # evaluate_model.lm_result calls stats::predict, compute_rmse, formula
    "models::evaluate_model.lm_result",
    "models::evaluate_model.lm_result",
    # compute_rmse calls sqrt, mean
    "models::compute_rmse",
    "models::compute_rmse",
    # run_benchmark calls its dependencies
    "benchmark::run_benchmark",
    "benchmark::run_benchmark",
    "benchmark::run_benchmark",
    "benchmark::run_benchmark",
    "benchmark::run_benchmark",
    "benchmark::run_benchmark",
    "benchmark::run_benchmark",
    # calculate_mrr calls mean
    "benchmark::calculate_mrr",
    # format_results calls sprintf, round, format
    "benchmark::format_results",
    "benchmark::format_results",
    "benchmark::format_results"
  ),
  to = c(
    "utils::read.csv",
    "dplyr::filter",
    "dplyr::mutate",
    "mean",
    "sd",
    "nrow",
    "floor",
    "seq_len",
    "stats::lm",
    "stats::predict",
    "models::compute_rmse",
    "sqrt",
    "mean",
    "data_prep::load_data",
    "data_prep::clean_data",
    "data_prep::split_data",
    "models::fit_model",
    "models::evaluate_model",
    "benchmark::calculate_mrr",
    "benchmark::format_results",
    "mean",
    "round",
    "format",
    "sprintf"
  ),
  stringsAsFactors = FALSE
)

saveRDS(call_edges, file.path(out_dir, "call_edges.rds"))
message("Wrote call_edges.rds (", nrow(call_edges), " edges)")

# ---- 3. node_relevance_scores.rds ------------------------------------
# Per-task ground-truth relevance scores.
# Each task is a plain-English query; each node gets a score 0-3:
#   0 = irrelevant, 1 = tangential, 2 = relevant, 3 = essential

tasks <- list(
  list(
    query = "How is input data loaded and validated?",
    scores = c(
      "data_prep::load_data" = 3L,
      "data_prep::clean_data" = 2L,
      "data_prep::split_data" = 1L,
      "data_prep::split_data.data.frame" = 0L,
      "models::fit_model" = 0L,
      "models::evaluate_model" = 0L,
      "models::evaluate_model.lm_result" = 0L,
      "models::compute_rmse" = 0L,
      "benchmark::run_benchmark" = 1L,
      "benchmark::calculate_mrr" = 0L,
      "benchmark::format_results" = 0L
    )
  ),
  list(
    query = "How is RMSE computed?",
    scores = c(
      "data_prep::load_data" = 0L,
      "data_prep::clean_data" = 0L,
      "data_prep::split_data" = 0L,
      "data_prep::split_data.data.frame" = 0L,
      "models::fit_model" = 1L,
      "models::evaluate_model" = 2L,
      "models::evaluate_model.lm_result" = 3L,
      "models::compute_rmse" = 3L,
      "benchmark::run_benchmark" = 1L,
      "benchmark::calculate_mrr" = 0L,
      "benchmark::format_results" = 0L
    )
  ),
  list(
    query = "How are benchmark results ranked and summarised?",
    scores = c(
      "data_prep::load_data" = 0L,
      "data_prep::clean_data" = 0L,
      "data_prep::split_data" = 0L,
      "data_prep::split_data.data.frame" = 0L,
      "models::fit_model" = 0L,
      "models::evaluate_model" = 1L,
      "models::evaluate_model.lm_result" = 1L,
      "models::compute_rmse" = 1L,
      "benchmark::run_benchmark" = 2L,
      "benchmark::calculate_mrr" = 3L,
      "benchmark::format_results" = 3L
    )
  )
)

saveRDS(tasks, file.path(out_dir, "node_relevance_scores.rds"))
message("Wrote node_relevance_scores.rds (", length(tasks), " tasks)")

message("\nGround truth generation complete.")
message("Total functions : ", length(function_signatures))
message("Total call edges: ", nrow(call_edges))
message("Total tasks     : ", length(tasks))
